### ISSUE TITLE
Color Picker strange behavior

### ISSUE THREAD

**Issue by sk33z3r** [you3h/LooPyGen_Client#14]
GIF at the end of the bug body to visually show the issue.

**Repro**:
1. Generate Background on Step 1
2. Add 2 or 3 variations for Background on Step 2
3. Pick colors and set other info for each variation
4. Remove any color, except the last one in the list

**Expected**:
Colors remain in the little square button to pull up the picture, correctly linked to the other info for the variation

**Actual**:
Any color variation in the list that shifts has a blank color picker button

**Notes**:
* I'm not sure if the value picked is still set or not, but when you click the blank button your original color is not there and the picker is reset.
* If you then add a new color variation, its color square will be default filled to the last color that was ocuppying this slot at step 3.

**GIF of the issue**

![gif_20220502_132333](https://user-images.githubusercontent.com/20587571/166300050-28f792a0-d6ca-48f8-9996-7d99674c0fb0.gif)

**Comment by sk33z3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React UI Updates needed for Local Release](https://trello.com/c/XocuDY35/23-react-ui-updates-needed-for-local-release)

**Comment by you3h** [comment]
Applied a fix to this issue, 

The issue happens because I'm storing the colors into an object and using the index as their key. so when one is deleted in the middle it doesn't move due to the index.

The fix I did is, whenever a delete happens I am adjusting all the savedColors object to move 1 index up and removing the last index.

It's available in this commit

https://github.com/you3h/LooPyGen_Client/commit/4d2efc6f48506ceb41cb9f924d9cbefca5d71f05

**Comment by sk33z3r** [comment]
Appears to work as expected, closing
